/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE `empresas` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`nome` VARCHAR(120) NOT NULL,
	`fantasia` VARCHAR(120) NOT NULL,
	`cnpj` VARCHAR(20) NOT NULL,
	`cpf` VARCHAR(15) NULL DEFAULT NULL,
	`ie` VARCHAR(20) NULL DEFAULT NULL,
	`ie_st` VARCHAR(20) NULL DEFAULT NULL,
	`im` VARCHAR(30) NULL DEFAULT NULL,
	`cnae` VARCHAR(12) NULL DEFAULT NULL,
	`suframa` VARCHAR(15) NULL DEFAULT NULL,
	`perfil` CHAR(1) NULL DEFAULT NULL,
	`ind_atividade` SMALLINT(3) NULL DEFAULT NULL,
	`uf` CHAR(2) NOT NULL,
	`ibge` INT NULL DEFAULT NULL,
	`cep` VARCHAR(10) NULL DEFAULT NULL,
	`logradouro` VARCHAR(120) NULL DEFAULT NULL,
	`numero` VARCHAR(10) NULL DEFAULT NULL,
	`complemento` VARCHAR(120) NULL DEFAULT NULL,
	`bairro` VARCHAR(120) NULL DEFAULT NULL,
	`fone` VARCHAR(15) NULL DEFAULT NULL,
	`celular` VARCHAR(15) NULL DEFAULT NULL,
	`email` VARCHAR(120) NULL DEFAULT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `cnpj` (`cnpj`) USING BTREE
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;


CREATE TABLE `usuarios` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`email` VARCHAR(255) NOT NULL,
	`nome` VARCHAR(255) NULL DEFAULT NULL,
	`password` VARCHAR(255) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `email` (`email`) USING BTREE
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS `recursos` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nome` varchar(60) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `nome` (`nome`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;


/*!40000 ALTER TABLE `recursos` DISABLE KEYS */;
INSERT INTO `recursos` (`nome`) VALUES
	('Empresa'),
	('Usuários'),
	('Recursos'),
	('Produtos'),
	('Setores'),
	('Unidades'),
	('Participantes'),
	('Pedidos'),
	('Notas Fiscais');
/*!40000 ALTER TABLE `recursos` ENABLE KEYS */;


CREATE TABLE `permissoes` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`usuario_id` INT NULL DEFAULT NULL,
	`recurso_id` INT NULL DEFAULT NULL,
	`c` TINYINT(1) NULL DEFAULT NULL,
	`r` TINYINT(1) NULL DEFAULT NULL,
	`u` TINYINT(1) NULL DEFAULT NULL,
	`d` TINYINT(1) NULL DEFAULT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`) USING BTREE,
	INDEX `usuario_id` (`usuario_id`) USING BTREE,
	INDEX `recurso_id` (`recurso_id`) USING BTREE,
	CONSTRAINT `usuario_fk` FOREIGN KEY (`usuario_id`) REFERENCES `usuarios` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `recurso_fk` FOREIGN KEY (`recurso_id`) REFERENCES `recursos` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;


/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;